/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package andreazelaya_examen2p2;

import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author andgz
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_addDeporte = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jt_nombreDep = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jd_addTorneo = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jt_nombreTorneo = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        cb_deportes = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jt_periodo = new javax.swing.JTextField();
        popup_dep = new javax.swing.JPopupMenu();
        agregarTorneo = new javax.swing.JMenuItem();
        popup_torneo = new javax.swing.JPopupMenu();
        jmi_agregarEquipo = new javax.swing.JMenuItem();
        jmi_listarEquipos = new javax.swing.JMenuItem();
        jmi_tablaPos = new javax.swing.JMenuItem();
        jmi_agregarPartido = new javax.swing.JMenuItem();
        jd_addEquipo = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jt_nombreEquipo = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jd_listEquipos = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jlist_equipos = new javax.swing.JList<>();
        jd_guardarDep = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        cb_deportes1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jd_agregarPartida = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        cb_e2 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jButton6 = new javax.swing.JButton();
        cb_e1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jd_descarga = new javax.swing.JDialog();
        jPanel10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jpb_barra = new javax.swing.JProgressBar();
        jd_tabla = new javax.swing.JDialog();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtable_puntos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jb_agregarDeporte = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jb_cargarDeporte = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainTree = new javax.swing.JTree();

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre del deporte: ");

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jt_nombreDep, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jButton1)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addComponent(jt_nombreDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_addDeporteLayout = new javax.swing.GroupLayout(jd_addDeporte.getContentPane());
        jd_addDeporte.getContentPane().setLayout(jd_addDeporteLayout);
        jd_addDeporteLayout.setHorizontalGroup(
            jd_addDeporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_addDeporteLayout.setVerticalGroup(
            jd_addDeporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 102));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre del torneo: ");

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Deporte");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Periodo");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jt_nombreTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jButton2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jt_periodo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(cb_deportes, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jt_nombreTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_deportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_periodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jButton2)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout jd_addTorneoLayout = new javax.swing.GroupLayout(jd_addTorneo.getContentPane());
        jd_addTorneo.getContentPane().setLayout(jd_addTorneoLayout);
        jd_addTorneoLayout.setHorizontalGroup(
            jd_addTorneoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_addTorneoLayout.setVerticalGroup(
            jd_addTorneoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        agregarTorneo.setText("Agregar torneo");
        agregarTorneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarTorneoActionPerformed(evt);
            }
        });
        popup_dep.add(agregarTorneo);

        jmi_agregarEquipo.setText("Agregar equipo");
        jmi_agregarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_agregarEquipoActionPerformed(evt);
            }
        });
        popup_torneo.add(jmi_agregarEquipo);

        jmi_listarEquipos.setText("Listar equipos");
        jmi_listarEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_listarEquiposActionPerformed(evt);
            }
        });
        popup_torneo.add(jmi_listarEquipos);

        jmi_tablaPos.setText("Mostrar tabla de posiciones");
        jmi_tablaPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_tablaPosActionPerformed(evt);
            }
        });
        popup_torneo.add(jmi_tablaPos);

        jmi_agregarPartido.setText("Agregar partido");
        jmi_agregarPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_agregarPartidoActionPerformed(evt);
            }
        });
        popup_torneo.add(jmi_agregarPartido);

        jPanel5.setBackground(new java.awt.Color(0, 0, 102));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre del equipo: ");

        jButton3.setText("Agregar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(135, 135, 135))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jt_nombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jButton3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel6)
                .addGap(38, 38, 38)
                .addComponent(jt_nombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton3)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_addEquipoLayout = new javax.swing.GroupLayout(jd_addEquipo.getContentPane());
        jd_addEquipo.getContentPane().setLayout(jd_addEquipoLayout);
        jd_addEquipoLayout.setHorizontalGroup(
            jd_addEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_addEquipoLayout.setVerticalGroup(
            jd_addEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(0, 0, 102));

        jlist_equipos.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jlist_equipos);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_listEquiposLayout = new javax.swing.GroupLayout(jd_listEquipos.getContentPane());
        jd_listEquipos.getContentPane().setLayout(jd_listEquiposLayout);
        jd_listEquiposLayout.setHorizontalGroup(
            jd_listEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_listEquiposLayout.setVerticalGroup(
            jd_listEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(0, 0, 102));

        jButton5.setText("Elegir lugar en donde guardar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Elegir deporte a guardar");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(cb_deportes1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jButton5)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(39, 39, 39)
                .addComponent(cb_deportes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jButton5)
                .addGap(81, 81, 81))
        );

        javax.swing.GroupLayout jd_guardarDepLayout = new javax.swing.GroupLayout(jd_guardarDep.getContentPane());
        jd_guardarDep.getContentPane().setLayout(jd_guardarDepLayout);
        jd_guardarDepLayout.setHorizontalGroup(
            jd_guardarDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_guardarDepLayout.setVerticalGroup(
            jd_guardarDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(153, 0, 0));

        jPanel9.setBackground(new java.awt.Color(0, 0, 102));

        cb_e2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Puntaje");

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        jButton6.setText("Registrar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(cb_e2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel9))
                            .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(25, 25, 25))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(cb_e2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel9)
                .addGap(31, 31, 31)
                .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(17, 17, 17))
        );

        cb_e1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Puntaje");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel7))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(cb_e1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(cb_e1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel7)
                .addGap(31, 31, 31)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_agregarPartidaLayout = new javax.swing.GroupLayout(jd_agregarPartida.getContentPane());
        jd_agregarPartida.getContentPane().setLayout(jd_agregarPartidaLayout);
        jd_agregarPartidaLayout.setHorizontalGroup(
            jd_agregarPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_agregarPartidaLayout.setVerticalGroup(
            jd_agregarPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel10.setBackground(new java.awt.Color(0, 0, 102));
        jPanel10.setForeground(new java.awt.Color(0, 0, 102));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Escribiendo...");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel10))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jpb_barra, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel10)
                .addGap(30, 30, 30)
                .addComponent(jpb_barra, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_descargaLayout = new javax.swing.GroupLayout(jd_descarga.getContentPane());
        jd_descarga.getContentPane().setLayout(jd_descargaLayout);
        jd_descargaLayout.setHorizontalGroup(
            jd_descargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_descargaLayout.setVerticalGroup(
            jd_descargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel11.setBackground(new java.awt.Color(0, 0, 102));

        jtable_puntos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Deporte", "Puntos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtable_puntos);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_tablaLayout = new javax.swing.GroupLayout(jd_tabla.getContentPane());
        jd_tabla.getContentPane().setLayout(jd_tablaLayout);
        jd_tablaLayout.setHorizontalGroup(
            jd_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_tablaLayout.setVerticalGroup(
            jd_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));

        jb_agregarDeporte.setText("Agregar deporte");
        jb_agregarDeporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_agregarDeporteActionPerformed(evt);
            }
        });

        jButton4.setText("Guardar deporte");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jb_cargarDeporte.setText("Cargar deporte");
        jb_cargarDeporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cargarDeporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_agregarDeporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_cargarDeporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jb_agregarDeporte, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_cargarDeporte, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        jLabel1.setFont(new java.awt.Font("FOT-NewRodin Pro DB", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Deportes UNITEC");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Torneos");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Q1");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Q2");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Q4");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Q5");
        treeNode1.add(treeNode2);
        mainTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        mainTree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainTreeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(mainTree);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel1)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_agregarDeporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_agregarDeporteActionPerformed
        jd_addDeporte.setModal(true);
        jd_addDeporte.pack();
        jd_addDeporte.setLocationRelativeTo(this);
        jd_addDeporte.setVisible(true);
    }//GEN-LAST:event_jb_agregarDeporteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Deporte d1 = new Deporte(jt_nombreDep.getText());

        deportes.add(d1);

        DefaultTreeModel modelo = (DefaultTreeModel) mainTree.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelo.getRoot();

        DefaultMutableTreeNode q1 = (DefaultMutableTreeNode) raiz.getChildAt(0);
        DefaultMutableTreeNode q2 = (DefaultMutableTreeNode) raiz.getChildAt(1);
        DefaultMutableTreeNode q4 = (DefaultMutableTreeNode) raiz.getChildAt(2);
        DefaultMutableTreeNode q5 = (DefaultMutableTreeNode) raiz.getChildAt(3);

        DefaultMutableTreeNode depNode = new DefaultMutableTreeNode(d1);
        DefaultMutableTreeNode depNode2 = new DefaultMutableTreeNode(d1);
        DefaultMutableTreeNode depNode3 = new DefaultMutableTreeNode(d1);
        DefaultMutableTreeNode depNode4 = new DefaultMutableTreeNode(d1);

        q1.add(depNode);
        q2.add(depNode2);
        q4.add(depNode3);
        q5.add(depNode4);

        jd_addDeporte.dispose();
        jt_nombreDep.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Torneo torneo = new Torneo(jt_nombreTorneo.getText(), Integer.parseInt(jt_periodo.getText()));
        int pos = cb_deportes.getSelectedIndex();
        deportes.get(pos).getTorneos().add(torneo);

        DefaultTreeModel modelo = (DefaultTreeModel) mainTree.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelo.getRoot();
        Object obj = mainTree.getSelectionPath().getLastPathComponent();
        DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) obj;

        DefaultMutableTreeNode t = new DefaultMutableTreeNode(torneo);
        nodo.add(t);

        modelo.reload();
        jd_addTorneo.dispose();
        jt_nombreTorneo.setText("");
        jt_periodo.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void mainTreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainTreeMouseClicked
        if (evt.getButton() == 3) {
            int row = mainTree.getClosestRowForLocation(evt.getX(), evt.getY());
            mainTree.setSelectionRow(row);

            DefaultTreeModel modelo = (DefaultTreeModel) mainTree.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelo.getRoot();
            Object obj = mainTree.getSelectionPath().getLastPathComponent();
            DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) obj;

            if (nodo.getUserObject() instanceof Deporte) {
                popup_dep.show(mainTree, evt.getX(), evt.getY());
            } else if (nodo.getUserObject() instanceof Torneo) {
                popup_torneo.show(mainTree, evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_mainTreeMouseClicked

    private void agregarTorneoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarTorneoActionPerformed
        refreshCBDep();
        jd_addTorneo.setModal(true);
        jd_addTorneo.pack();
        jd_addTorneo.setLocationRelativeTo(this);
        jd_addTorneo.setVisible(true);
    }//GEN-LAST:event_agregarTorneoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Equipo e = new Equipo(jt_nombreEquipo.getText());

        DefaultTreeModel modelo = (DefaultTreeModel) mainTree.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelo.getRoot();
        Object obj = mainTree.getSelectionPath().getLastPathComponent();
        DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) obj;
        Torneo t = (Torneo) nodo.getUserObject();

        t.getEquipos().add(e);
        System.out.println(deportes);
        jd_addEquipo.dispose();
        jt_nombreEquipo.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jmi_agregarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_agregarEquipoActionPerformed
        jd_addEquipo.setModal(true);
        jd_addEquipo.pack();
        jd_addEquipo.setLocationRelativeTo(this);
        jd_addEquipo.setVisible(true);
    }//GEN-LAST:event_jmi_agregarEquipoActionPerformed

    private void jmi_listarEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_listarEquiposActionPerformed
        DefaultTreeModel modelo = (DefaultTreeModel) mainTree.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelo.getRoot();
        Object obj = mainTree.getSelectionPath().getLastPathComponent();
        DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) obj;
        Torneo t = (Torneo) nodo.getUserObject();

        refreshListEquipos(t);

        jd_listEquipos.setModal(true);
        jd_listEquipos.pack();
        jd_listEquipos.setLocationRelativeTo(this);
        jd_listEquipos.setVisible(true);
    }//GEN-LAST:event_jmi_listarEquiposActionPerformed

    private void jb_cargarDeporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cargarDeporteActionPerformed
        JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivo Binario", "bin");
        jfc.setFileFilter(filtro);
        int seleccion = jfc.showSaveDialog(this);
        File archivo = jfc.getSelectedFile();
        if (seleccion == JFileChooser.APPROVE_OPTION) {

            BinariosDeportes bD = new BinariosDeportes(archivo.getPath());
            bD.cargar();

            Deporte d = bD.getDeporte();
            deportes.add(d);

            ArrayList<Torneo> tempArray = d.getTorneos();
            System.out.println();

            DefaultTreeModel modelo = (DefaultTreeModel) mainTree.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelo.getRoot();

            DefaultMutableTreeNode q1 = (DefaultMutableTreeNode) raiz.getChildAt(0);
            DefaultMutableTreeNode q2 = (DefaultMutableTreeNode) raiz.getChildAt(1);
            DefaultMutableTreeNode q4 = (DefaultMutableTreeNode) raiz.getChildAt(2);
            DefaultMutableTreeNode q5 = (DefaultMutableTreeNode) raiz.getChildAt(3);

            DefaultMutableTreeNode depNode = new DefaultMutableTreeNode(d);
            DefaultMutableTreeNode depNode2 = new DefaultMutableTreeNode(d);
            DefaultMutableTreeNode depNode3 = new DefaultMutableTreeNode(d);
            DefaultMutableTreeNode depNode4 = new DefaultMutableTreeNode(d);

            for (int i = 0; i < d.getTorneos().size(); i++) {
                System.out.println(d.getTorneos().get(i).periodo);
                if (d.getTorneos().get(i).periodo == 1) {
                    DefaultMutableTreeNode torneo = new DefaultMutableTreeNode(d.getTorneos().get(i));
                    depNode.add(torneo);
                } else if (d.getTorneos().get(i).periodo == 2) {
                    DefaultMutableTreeNode torneo = new DefaultMutableTreeNode(d.getTorneos().get(i));
                    depNode2.add(torneo);
                } else if (d.getTorneos().get(i).periodo == 4) {
                    DefaultMutableTreeNode torneo = new DefaultMutableTreeNode(d.getTorneos().get(i));
                    depNode3.add(torneo);
                } else if (d.getTorneos().get(i).periodo == 5) {
                    DefaultMutableTreeNode torneo = new DefaultMutableTreeNode(d.getTorneos().get(i));
                    depNode4.add(torneo);
                }
            }

            q1.add(depNode);
            q2.add(depNode2);
            q4.add(depNode3);
            q5.add(depNode4);

            modelo.reload();

        }
    }//GEN-LAST:event_jb_cargarDeporteActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivo Binario", "bin");
        jfc.setFileFilter(filtro);
        int seleccion = jfc.showSaveDialog(this);
        File archivo = jfc.getSelectedFile();
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            progressBar pb = new progressBar(jpb_barra, ((Deporte) cb_deportes1.getSelectedItem()).getTorneos().size(), jd_descarga);
            pb.start();

            jd_descarga.setModal(true);
            jd_descarga.pack();
            jd_descarga.setLocationRelativeTo(this);
            jd_descarga.setVisible(true);

            BinariosDeportes bD = new BinariosDeportes(archivo.getPath() + ".bin");
            bD.setDeporte(((Deporte) cb_deportes1.getSelectedItem()));
            bD.escribir();
            jd_guardarDep.dispose();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        refreshCBDep1();
        jd_guardarDep.setModal(true);
        jd_guardarDep.pack();
        jd_guardarDep.setLocationRelativeTo(this);
        jd_guardarDep.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jmi_agregarPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_agregarPartidoActionPerformed
        DefaultTreeModel modelo = (DefaultTreeModel) mainTree.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelo.getRoot();
        Object obj = mainTree.getSelectionPath().getLastPathComponent();
        DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) obj;
        Torneo t = (Torneo) nodo.getUserObject();

        refreshCBEquipos(t, cb_e1);
        refreshCBEquipos(t, cb_e2);
        jd_agregarPartida.setModal(true);
        jd_agregarPartida.pack();
        jd_agregarPartida.setLocationRelativeTo(this);
        jd_agregarPartida.setVisible(true);
    }//GEN-LAST:event_jmi_agregarPartidoActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        DefaultTreeModel modelo = (DefaultTreeModel) mainTree.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelo.getRoot();
        Object obj = mainTree.getSelectionPath().getLastPathComponent();
        DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) obj;
        Torneo t = (Torneo) nodo.getUserObject();

        DefaultComboBoxModel model1 = (DefaultComboBoxModel) cb_e1.getModel();
        Equipo dep1 = (Equipo) model1.getSelectedItem();
        dep1.setPuntos(dep1.getPuntos() + (Integer) jSpinner1.getValue());

        DefaultComboBoxModel model2 = (DefaultComboBoxModel) cb_e2.getModel();
        Equipo dep2 = (Equipo) model2.getSelectedItem();
        dep2.setPuntos(dep2.getPuntos() + (Integer) jSpinner2.getValue());

        Partido p = new Partido(dep1, dep2);
        
        jSpinner1.setValue(0);
        jSpinner2.setValue(0);
        jd_agregarPartida.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jmi_tablaPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_tablaPosActionPerformed
        refreshTabla();
        
        jd_tabla.setModal(true);
        jd_tabla.pack();
        jd_tabla.setLocationRelativeTo(this);
        jd_tabla.setVisible(true);
    }//GEN-LAST:event_jmi_tablaPosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    public void refreshListEquipos(Torneo t) {
        DefaultListModel modelo = (DefaultListModel) jlist_equipos.getModel();
        for (Equipo e : t.getEquipos()) {
            modelo.addElement(e);
        }
        jlist_equipos.setModel(modelo);

    }

    public void refreshCBEquipos(Torneo t, JComboBox c) {
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) c.getModel();
        modelo.removeAllElements();
        for (Equipo e : t.getEquipos()) {
            modelo.addElement(e);
        }
        c.setModel(modelo);

    }

    public void refreshCBDep() {
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_deportes.getModel();
        modelo.removeAllElements();

        for (Deporte dep : deportes) {
            modelo.addElement(dep);
        }
        jd_addTorneo.dispose();
    }

    public void refreshCBDep1() {
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_deportes1.getModel();
        modelo.removeAllElements();

        for (Deporte dep : deportes) {
            modelo.addElement(dep);
        }
    }

    public void refreshTabla() {
        DefaultTreeModel modelo = (DefaultTreeModel) mainTree.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelo.getRoot();
        Object obj = mainTree.getSelectionPath().getLastPathComponent();
        DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) obj;
        Torneo t = (Torneo) nodo.getUserObject();
        
        sort(t);
        Collections.reverse(t.getEquipos());

        DefaultTableModel modeloTabla = (DefaultTableModel) jtable_puntos.getModel();
        modeloTabla.setRowCount(0);
        for (Equipo e : t.getEquipos()) {
            Object [] datos = {e.getNombre(),e.getPuntos()};
            modeloTabla.addRow(datos);
        }

    }

    public void sort(Torneo t) {
        int n = t.getEquipos().size();
        for (int i = 0; i < n - 1; i++) {
            for (int j = 0; j < n - i - 1; j++) {
                if (t.getEquipos().get(j).getPuntos() > t.getEquipos().get(j + 1).getPuntos()) {
                    Equipo temp = t.getEquipos().get(j);
                    t.getEquipos().set(j, t.getEquipos().get(j + 1));
                    t.getEquipos().set(j + 1, temp);
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem agregarTorneo;
    private javax.swing.JComboBox<String> cb_deportes;
    private javax.swing.JComboBox<String> cb_deportes1;
    private javax.swing.JComboBox<String> cb_e1;
    private javax.swing.JComboBox<String> cb_e2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JButton jb_agregarDeporte;
    private javax.swing.JButton jb_cargarDeporte;
    private javax.swing.JDialog jd_addDeporte;
    private javax.swing.JDialog jd_addEquipo;
    private javax.swing.JDialog jd_addTorneo;
    private javax.swing.JDialog jd_agregarPartida;
    private javax.swing.JDialog jd_descarga;
    private javax.swing.JDialog jd_guardarDep;
    private javax.swing.JDialog jd_listEquipos;
    private javax.swing.JDialog jd_tabla;
    private javax.swing.JList<String> jlist_equipos;
    private javax.swing.JMenuItem jmi_agregarEquipo;
    private javax.swing.JMenuItem jmi_agregarPartido;
    private javax.swing.JMenuItem jmi_listarEquipos;
    private javax.swing.JMenuItem jmi_tablaPos;
    private javax.swing.JProgressBar jpb_barra;
    private javax.swing.JTextField jt_nombreDep;
    private javax.swing.JTextField jt_nombreEquipo;
    private javax.swing.JTextField jt_nombreTorneo;
    private javax.swing.JTextField jt_periodo;
    private javax.swing.JTable jtable_puntos;
    private javax.swing.JTree mainTree;
    private javax.swing.JPopupMenu popup_dep;
    private javax.swing.JPopupMenu popup_torneo;
    // End of variables declaration//GEN-END:variables

    ArrayList<Deporte> deportes = new ArrayList();

}
